version: '2'
services:
 nginx:
    build: nginx
    container_name: nginx
    ports: 
      - 8080:80
      - 443:443
    volumes: 
      - ./www:/usr/share/nginx/html
 php-fpm:
    image: nanoninja/php-fpm
    container_name: php-fpm
    volumes:
      - ./www:/usr/share/nginx/html
 db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123

